### ISSUE TITLE
Error in command prompt

### ISSUE THREAD

**Issue by CakeWut-git** [DC37/Super-Mario-Paint#20]
I was just making a song then this popped up in the SMP command prompt:

java.lang.IndexOutOfBoundsException: Index: 10, Size: 10
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at javafx.scene.Scene$MouseHandler.handleNodeRemoval(Unknown Source)
at javafx.scene.Scene$MouseHandler.access$7400(Unknown Source)
at javafx.scene.Scene.generateMouseExited(Unknown Source)
at javafx.scene.Parent$2.onProposedChange(Unknown Source)
at com.sun.javafx.collections.VetoableListDecorator.clear(Unknown Source)
at smp.components.staff.NoteMatrix.clearNoteDisplay(NoteMatrix.java:267)
at smp.components.staff.NoteMatrix.redraw(NoteMatrix.java:189)
at smp.components.staff.NoteMatrix.redraw(NoteMatrix.java:164)
at smp.components.staff.Staff$1.run(Staff.java:201)
at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
at com.sun.javafx.application.PlatformImpl$$Lambda$48/16333776.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
at com.sun.javafx.application.PlatformImpl$$Lambda$47/8336391.run(Unknown Source)
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
at com.sun.glass.ui.win.WinApplication$$Lambda$38/24963482.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

**Comment by DC37** [comment]
Did anything crash?
Or did it still continue to function?

**Comment by CakeWut-git** [comment]
Nothing crashed. Everything still functioned.

**Comment by CakeWut-git** [comment]
Just played with it some more; it has to do with the notes disappearing.

**Comment by DC37** [comment]
Did this happen in a previous version? I think I know what the issue is, but I haven't been able to fix it / find time to do it.

**Comment by CakeWut-git** [comment]
This bug happened in 1.0.2.

**Comment by DC37** [comment]
Got it. Thanks for being patient as I try to work through both these program bugs and also deal with real life.

**Comment by DC37** [comment]
Closing unless there are problems in v1.0.3

**Comment by CakeWut-git** [comment]
The error still happens in v1.0.3.

**Comment by DC37** [comment]
I have found a partial answer to the error, it has to do with the staff re-drawing itself but not doing that fast enough, and some threading issues. Working on fixing it right now, it's not an easy one.
