### ISSUE TITLE
App fails to launch on Linux

### ISSUE THREAD

**Issue by genericCandy** [DC37/Super-Mario-Paint#61]
When I try to launch the `jar` using `java -jar SMPv1.4.3.jar`, I get the following error message:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:495)
        at java.base/java.lang.Class.forName(Class.java:474)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:59)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 14 more
```

# Expected behavior
App launches

# JDK Versions
OpenJDK 11, OpenJDK 19, Oracle JDK 19 (none of them work)

# OS Info
- OS: Manjaro Linux x86_64
- Kernel: 5.15.89-1-MANJARO

**Comment by RainShinotsu** [comment]
I had this issue too and got it fixed in the Mario Paint Hangout Discord server. You need to have JavaFX installed, which isn't provided by OpenJDK, then make sure to run the extra JFX dependencies with the SMP jarfile.

On Manjaro, your best bet might be using Java 11, since the Manjaro repos don't provide JFX for Java 8. The packages you need would be `jre11-openjdk` and `java11-openjfx`. Then, to launch the software, use the command `/usr/lib/jvm/java-11-openjdk/bin/java --add-modules=ALL-MODULE-PATH -p "/usr/lib/jvm/java-11-openjfx/lib/javafx.base.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.controls.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.fxml.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.graphics.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.media.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.swing.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.web.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx-swt.jar" -jar SMPv1.4.3.jar` (replacing `SMPv1.4.3.jar` with your SMP version's filename. Make sure your terminal is in the directory with the jarfile, otherwise you'll have to write out the full file path to SMP instead of just the jarfile name.

Since that's a long command, you might want to make a shell script to run SMP. Paste this into a new file and save it in your SMP directory as any filename with the `.sh` extension: ```#!/bin/sh
/usr/lib/jvm/java-11-openjdk/bin/java --add-modules=ALL-MODULE-PATH -p /usr/lib/jvm/java-11-openjfx/lib/javafx.base.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.controls.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.fxml.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.graphics.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.media.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.swing.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx.web.jar:/usr/lib/jvm/java-11-openjfx/lib/javafx-swt.jar -jar SMPv1.4.3.jar``` (make sure to update this file with new SMP versions, because it probably won't be 1.4.3 forever).

**Comment by DC37** [comment]
@genericCandy v1.4.4 possibly addresses this. https://github.com/DC37/Super-Mario-Paint/releases/tag/v1.4.4
Commit d0bd07
Could you check this?

**Comment by DC37** [comment]
Closing, can reopen if there is still trouble.
